name: reach_auth
description: A new Flutter package project.
version: 0.0.1
publish_to: none
homepage:

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # reach_core:

  #   path: /Users/fahad/AndroidStudioProjects/reach_researchers/packages/reach_core
   
  reach_core:
    git: 
      url: https://github.com/FahadMajed/reach_core
      ref: dev
  firebase_auth: ^4.0.0

  sign_in_with_apple: ^3.2.0



  google_sign_in_platform_interface: ^2.2.0
  quiver: ^3.0.0
  google_sign_in: ^5.4.2


dev_dependencies:
  build_runner: 2.1.2 
  json_serializable: ^5.0.2
  test: ^1.19.2
  # fake_cloud_firestore: any
  flutter_lints: any
  # flutter_test:
  #   sdk: flutter

  flutter_launcher_icons: 0.9.1